### ISSUE TITLE
组织管理员新建部门或人员的时候，所属部门不应该有默认值

### ISSUE THREAD

**Issue by yinlianghui** [steedos/creator#1017]
- 新建/编辑部门时，上级部门属性，组织管理员只能选择当前用户所属单位范围内的部门
- 新建/编辑部门时，所属部门属性，组织管理员只能选择当前用户所属单位范围内的部门
- 字段的is_company_limited属性判断权限时，与字段所属对象viewAllRecords权限关联，但是users/spaceusers/organizations三个对象与modifiyAllRecords权限关联
- 以上规则中，系统管理员选择范围是全部，因为系统管理员有modifiyAllRecords权限
- 新建部门时，上级部门默认值去掉
- 新建人员时，因为需要在左侧有选中组织时，默认设置所属部门为选中组织，所以保留了默认值
![image](https://user-images.githubusercontent.com/6219465/52034961-7025e600-2564-11e9-8044-f0cf8d3d3dcf.png)

**Comment by steedos** [comment]
不需要判断
