### ISSUE TITLE
字段使用master_detail和lookup类型，关联到其他表，应该可以配置过滤条件，目前是获得全部表内容

### ISSUE THREAD

**Issue by liminglang** [steedos/creator#102]

**Comment by liminglang** [comment]
具体用法如：
archive_destroy_id:
			type:"master_detail"
			label:"销毁单"
			filters:[["destroy_state", "$eq", "未销毁"]]
			depend_on:["destroy_state"]
			reference_to:"archive_destroy"
			group:"销毁"

**Comment by steedos** [comment]
重复
