### ISSUE TITLE
报表选择字段改进

### ISSUE THREAD

**Issue by steedos** [steedos/creator#1042]
- [x] 把隐藏字段去掉，包括相关表也不需要显示隐藏字段
- [x] 主表的字段列在最前面；
- [ ] 如果是相关表字段，直接引用 字段名.名称。
- [ ] 内嵌的字段，不能统计就全部跳过，不在要报表字段列表中列出来让用户选择。
- [ ] => 改为 .
- [x] 没有选择对象时，不能选择字段

**Comment by yinlianghui** [comment]
关于`如果是相关表字段，直接引用 字段名.名称。`：
这个在列表选项中显示为“提报单位.名称”还是说显示“提报单位”但是最后统计的时候按"提报单位.名称"来统计?
