### ISSUE TITLE
在action里使用查询，只能查询到界面上显示的字段，一些不显示的字段值查不到

### ISSUE THREAD

**Issue by liminglang** [steedos/creator#105]
action中如果需要使用数据项，应该从服务器调用odata接口抓取数据

**Comment by steedos** [comment]
列表页在执行action之前，先从服务器抓取数据？

**Comment by liminglang** [comment]
先不处理，如果需要处理的话，考虑在执行action的todo之前，先通过odata接口，把所有数据抓过来

**Comment by yinlianghui** [comment]
经讨论，该任务不用处理，在详细界面写action的todo就好了
