### ISSUE TITLE
信息上报需求

### ISSUE THREAD

**Issue by steedos** [steedos/creator#11]
股份信息上报过程：
1.股份各基层单位文书把每日的信息上报到系统中；
2.秘书科全体成员可以看到每天上报的信息，并打分，然后选择“是否采用”；
3.所有上报的信息能够汇总成一个表格（每月一汇总），汇总内容主要是每个基层单位的报送数量、采用数量等。
4.股份秘书科根据上报信息，拟写“秦港股份信息”表单，然后给领导审阅。

信息上报的功能：
1.类似于组织架构的功能，左侧是各基层单位的树状图（按照报送时间倒序）。右侧是内容区
2.点击左侧的单位（报送时间），对应右边应出现该单位上报的信息。
3.上报信息显示样式：
【大字体】文件标题
【其他字体】内容
【其他字体】报送公司   更多
操作：打分    是否采用
4.打分形式：正常采用+5   领导批示+10   月度好信息+5   上级采用+5
5.汇总、导出功能，自定义（开始时间-结束时间）
汇总内容：序号、单位、报送数量、采用数量、总分

**Comment by liminglang** [comment]
1.按字段查询，如按报送公司过滤
