### ISSUE TITLE
QHD档案归并入master

### ISSUE THREAD

**Issue by marchtian** [steedos/creator#1120]
主要工作
- [x]  以master分支为基础、新建master-from-archive分支，归并入qhd的archive的3个包
- [x]  解决master-from-archive分支上的问题
- [ ]  master-from-archive分支 归并入 master分支

待处理事项
- [ ]  以全宗为基础（而不是orgnization），实现切换单位的机制 https://github.com/steedos/creator/issues/1121
- [ ]  查找，销毁文件的filter引发的错误 https://github.com/steedos/creator/issues/1122
- [ ]  grid，关于字段宽度与排序的归并 https://github.com/steedos/creator/issues/1123

**Comment by chenzhipei** [comment]
不处理
