### ISSUE TITLE
查找页，分组里的searchable、filterable的字段不会显示在最上面

### ISSUE THREAD

**Issue by marchtian** [steedos/creator#1139]
![image](https://user-images.githubusercontent.com/7553007/57288330-d6824d80-70eb-11e9-90f9-fc1799144e1e.png)
那么，查找页，这个字段不会显示在上面
![image](https://user-images.githubusercontent.com/7553007/57288389-f1ed5880-70eb-11e9-8110-509e1f4fc22a.png)

**Comment by baozhoutao** [comment]
当字段的searchable或filterable设置为true 并且有group时， 是将这字段的group去掉

**Comment by zhuangjianguo666** [comment]
测试推送 @sunhaolin

**Comment by marchtian** [comment]
qhd档案，该功能已上线
