### ISSUE TITLE
编辑页面，部分字段修改后无效

### ISSUE THREAD

**Issue by marchtian** [steedos/creator#1182]
![image](https://user-images.githubusercontent.com/7553007/59319206-61aebe80-8cfc-11e9-8d1c-f6d3e758f615.png)
例如上图中，禁用操作、不可编辑字段 目前是有值的，想去掉这个值，点×，再点保存，刷新后发现 禁用操作、不可编辑字段 仍然有值

**Comment by baozhoutao** [comment]
此问题是由于目前的odata接口不支持$unset 参数导致，处理方案为：odata接口获取到$set, $unset 后， 将set与unset合并为一个doc ，交给driver。 合并完的doc中，unset字段部分字段值均为null
