### ISSUE TITLE
iPhone手机版，对象记录显示时，点击附件后无法返回原对象记录页

### ISSUE THREAD

**Issue by marchtian** [steedos/creator#1272]
进合同管理后，点开某合同记录
![手机附件返回1](https://user-images.githubusercontent.com/7553007/62597930-2a364a00-b91a-11e9-9569-f602f178d75a.png)
点击某附件
![手机附件返回2](https://user-images.githubusercontent.com/7553007/62597955-36baa280-b91a-11e9-8a69-3867913e0274.png)
只有左上角的 “X”，点击则退出当前应用、而不是回到刚才的 某个合同记录页面

**Comment by yinlianghui** [comment]
应该是这个原因：手机浏览器点击附件会跳转到首页 #1300
需要android真机测试下，ios上打不到附件，但是不会跳转到首页了。
