### ISSUE TITLE
iPhone手机版，点击查看完相关对象后返回，附件、相关对象列表显示异常（Android正常）

### ISSUE THREAD

**Issue by marchtian** [steedos/creator#1274]
进某合同记录
![手机附件返回1](https://user-images.githubusercontent.com/7553007/62598446-fd833200-b91b-11e9-8544-b6dce93fb359.png)
点击相关的验收记录
![手机相关对象返回2](https://user-images.githubusercontent.com/7553007/62598470-0d9b1180-b91c-11e9-8dbe-6b59be434f15.png)
点击左上的“<” ,返回的对象记录页如下
![手机相关对象返回3](https://user-images.githubusercontent.com/7553007/62598515-33c0b180-b91c-11e9-946f-7ca3b9e1668a.png)

其中，附件不见了，相关验收 显示“无数据”

**Comment by marchtian** [comment]
beta部署，没再现此问题

**Comment by baozhoutao** [comment]
#1309 处理从相关记录页面返回时，相关列表数据显示异常 5f952ccc
