### ISSUE TITLE
iPhone手机版，无法查看相关审批单

### ISSUE THREAD

**Issue by marchtian** [steedos/creator#1276]
进入某合同记录
![手机查看相关审批单](https://user-images.githubusercontent.com/7553007/62599213-391efb80-b91e-11e9-8aca-2a944e1aa30f.png)
点击相关审批，
![手机查看相关审批单2](https://user-images.githubusercontent.com/7553007/62599233-4340fa00-b91e-11e9-8f50-41a8090d265b.png)
点击“查看审批单”，无反应。
Andoird上点击后，则会出现PC版的审批单原貌。

**Comment by yinlianghui** [comment]
最新代码PC上也是坏的，qhd-beta线上PC上是好的
