### ISSUE TITLE
iPhone手机版，报表显示不全、无法滚动（Android可以滚动的）

### ISSUE THREAD

**Issue by marchtian** [steedos/creator#1278]
![手机报表](https://user-images.githubusercontent.com/7553007/62600651-f8c17c80-b921-11e9-9f0e-405e5c4251d8.png)
包括JSReport的报表，都是这样，没有水平和垂直的滚动条。
Android上有滚动条。

**Comment by yinlianghui** [comment]
经测试app及浏览器上iphone都是可以有滚动条，且能正常滚动的

**Comment by marchtian** [comment]
QHD合同，手机上去掉 报表，beta已上线
