### ISSUE TITLE
参考Salesforce样式，优化手机端界面

### ISSUE THREAD

**Issue by hotlong** [steedos/creator#1309]
- 统一手机端和电脑端main template
- 类似华信，开发左侧折叠菜单，列出所有应用和应用下的对象。

**Comment by hotlong** [comment]
https://trailhead.salesforce.com/content/learn/modules/salesforce1_mobile_app/salesforce1_mobile_app_navigation

**Comment by baozhoutao** [comment]
app 新增 mobile_objects ：用于指定哪些对象在手机上显示
