### ISSUE TITLE
Steedos oAuth2 Server

### ISSUE THREAD

**Issue by steedos** [steedos/creator#131]
https://github.com/prime-8-consulting/meteor-oauth2

- 新开发包 steedos:oauth2-server
- 按照这个流程开发oAuth2 协议
- 使用 Creator 创建相关对象的维护界面，供管理员使用

功能需求：
1.类似于企业微信的授权登录。
2.做一个登录界面和一个授权认证的弹出窗口。
3.oauth2涉及的表按照工作区进行区分。
4.管理员维护OAuth2Clients表。
表中字段：
"clientId" : string
 "active" : boolen,默认是true
"redirectUri" :string 网址正则表达式
"clientSecret" : string
"clientName" : string
5.如果当前用户授权过该应用，则无需再次授权，直接登录。

**Comment by zonglu233** [comment]
测试要点：
1.管理员维护：
- [ ] 管理员可以通过oauth2的维护模块，对第三方应用进行维护。其中，clientId和clientSecret是根据meteor自带的接口生成，不需要填写，但可以显示。

2.授权登录
- [ ] 第三方应用跳转至授权登录对应的路径，如果creator用户已经登录，则直接跳转到授权页面，如果未登录，则跳转至登录界面，登录成功后，则跳转至授权页面。
- [ ] 在授权页面，如果用户在同一浏览器曾授权过该应用，则默认是允许授权，直接发送授权码给第三方应用。
- [ ] 第三方应用根据授权码获取access_token，并使用access_token调取获取用户信息接口获取当前用户信息。
