### ISSUE TITLE
odata那边viewCompanyRecords权限判断可能有问题，当传入要返回哪些字段的参数时权限判断不对

### ISSUE THREAD

**Issue by yinlianghui** [steedos/creator#1325]
![image](https://user-images.githubusercontent.com/6219465/64578060-d3a4ab80-d3b0-11e9-92f3-f17e3603e234.png)

重现方法：
- 找一个当前账户本来是有权限访问的单位级权限对象数据
- 用Creator.odata.get('xxx', 'xxx')访问，返回的是能访问到结果
- 用Creator.odata.get('xxx', 'xxx','name')访问却提示不能访问

> 可以把对象的viewAllRecords设置为false，viewCompanyRecords设置为true来重现问题
![image](https://user-images.githubusercontent.com/6219465/64578331-adcbd680-d3b1-11e9-9c00-9218eddf631c.png)

**Comment by sunhaolin** [comment]
根据重现方法未能重现出问题
