### ISSUE TITLE
users表与space_users表中username同步问题

### ISSUE THREAD

**Issue by yinlianghui** [steedos/creator#1360]
问题现象：有些数据users表里有用户名，space_users里没有。

相关任务：
- [x] 要确认下目前管理员增加修改用户时，username在两个表中的同步功能是正常
- [x] 要确认下注册用户、用户自己修改username时，username在两个表中的同步功能是正常
- [ ] 要确认下导入用户时，username在两个表中的同步功能是正常
- [ ] 升级脚本要写并在相关平台执行，目前已经有migrate脚本文件但是空的

现在用户名同步的机制，看了下creator最新代码，规则如下：
1.管理员添加修改用户space_users记录，会自动同步到users表
2.用户注册时会新增users记录，但是其username不会同步到space_users中
3.个人账户中修改user表的username值，不会同步到space_users中

> 注意：因为目前已经有空的migrate脚本文件，对于脚本已经执行过的平台，需要清空 .migrate文件夹来执行脚本，否则不会执行

老的脚本任务：新增字段，space_users.username，方便工作区管理员改用户名 #864

**Comment by sunhaolin** [comment]
https://github.com/steedos/steedos-accounts/issues/42

**Comment by sunhaolin** [comment]
https://github.com/steedos/steedos-accounts/issues/44
