### ISSUE TITLE
审批王表单模式默认值问题

### ISSUE THREAD

**Issue by yinlianghui** [steedos/creator#1362]
现象：表单配置的是表格模式， 打印界面也是正常的， 但是编辑界面显示的是默认样式
![image](https://user-images.githubusercontent.com/6219465/65827166-03fdac80-e2c2-11e9-9aa8-1032360915c8.png)

原因：creator中新建的流程，对应的表单“样式”属性为空，而审批王那边为空时取的值是“默认”

理论上新建流程的时候默认值设置为table/default应该就解决了该问题，但是standard-object中我设置了默认值未能生效，估计是后台新建表单时没走defaultValue配置！

![image](https://user-images.githubusercontent.com/6219465/65827602-563fcd00-e2c4-11e9-8f40-0cc91865698c.png)

**Comment by sunhaolin** [comment]
已修改新建表单接口：默认值为 table
