### ISSUE TITLE
提交申请单报错

### ISSUE THREAD

**Issue by baozhoutao** [steedos/creator#1364]
![image](https://user-images.githubusercontent.com/6194462/65829452-492cd900-e2d8-11e9-91a8-42e2a99c6dbd.png)

- 是steedos-workflow包中`db.instance_record_queue = new Meteor.Collection('instance_record_queue')`这行代码注释造成的
- 是在申请单到对象的同步 settings 配置了cron.instancerecordqueue_interval 才会执行的。

**Comment by yinlianghui** [comment]
同时把db.instance_record_queue定义为standard-object了
https://github.com/steedos/object-server/commit/62f30cad69f0ce78836d167c73e8e6f7e345872e
