### ISSUE TITLE
优化客户端、浏览器端推送通知

### ISSUE THREAD

**Issue by hotlong** [steedos/creator#1377]
我们的推送通知用的 $.notification ，自从2015年就没有更新过。

creator已知问题

$.notification 不存在

在最新版本的Chrome浏览器上。老版本的审批王也有问题。以下代码收不到。

var options = {
    iconUrl: 'avatar.png',
    title: 'Title',
    body: 'Message',
    onclick: function () {
        console.log('Pewpew');
    }
};

$.notification(options);

开发后需要在新版的客户端测试确认推送通知。

**Comment by hotlong** [comment]
目前测试下来最稳定的发送推送通知的是这个： https://pushjs.org/ ，包括华炎办公老的客户端，新版客户端，Chrome, Safari, Edge 都可以。官网宣称IE也可以

**Comment by yinlianghui** [comment]
> 目前测试下来最稳定的发送推送通知的是这个： https://pushjs.org/ ，包括华炎办公老的客户端，新版客户端，Chrome, Safari, Edge 都可以。官网宣称IE也可以
存在问题：

- [ ] win10华信客户端不支持
- [ ] win10审批王客户端，待确认是否支持
- [ ] IE不支持
- [ ] 部分平台不能提示是否允许通知选项，有可能部署到https就会提示
- [ ] 有时刷新浏览器会弹出最后一个老通知
