### ISSUE TITLE
信息上报最新问题

### ISSUE THREAD

**Issue by liminglang** [steedos/creator#139]
- [x]  内容在列表显示时给定最大高度（4行）
- [x]  详细信息里的内容要全部显示
- [x]  根据信息内容和报送单位进行搜索（已建议issuehttps://github.com/steedos/creator/issues/140）
- [x]  希望字号能稍微小一点
- [x]  报送时间排序不对
- [x]  报表的柱状图不需要
- [x] 杂货公司文书上报的信息，列表显示不全（目前是从3月15号之后上报的信息都看不到了）
- [x] 二公司的各信息上报员，在“本公司”视图下，看不到其他人的上报信息。(目前本地无法重现）

**Comment by steedos** [comment]
报表的列名希望用（报送数量，采用数量，总分），此问题受报表工具的限制，不处理。

**Comment by lizhenghotoa** [comment]
报送时间排序问题 暂时没问题
