### ISSUE TITLE
用户设置了email 后，userSession.email 为空

### ISSUE THREAD

**Issue by baozhoutao** [steedos/creator#1404]
userSession.email 来自 user.email 。user.email 是 通过验证的并且设置为主邮件。creator中没有将用户的邮件设置为主邮件功能，所以userSession.email 为空

**Comment by sunhaolin** [comment]
由 (user, space_user 数据结构及功能调整 #44)[https://github.com/steedos/steedos-accounts/issues/44] 重新设计
