### ISSUE TITLE
路由跳转 /app/-/instances/:id 应该跳转到申请单对应的箱

### ISSUE THREAD

**Issue by hotlong** [steedos/creator#1405]
可以先用odata抓取申请单的信息，再决定跳转地址

**Comment by yinlianghui** [comment]
- 未用odata抓取申请单去判断走哪个箱，而是新增加了后台api来重定向到关联箱子了
- 前端路由`/app/:app_id/instances/view/:record_id`自动调用上述新增api接口重定向到关联申请单界面了
- 兼容考虑了rootURL配置
