### ISSUE TITLE
最近查看即object_recent_viewed表中数据返回两种格式，应该是删除记录时未把object_recent_viewed表中对应记录删除

### ISSUE THREAD

**Issue by yinlianghui** [steedos/creator#1406]
- 访问这个url的链接能直接看到所有对象的最近查看记录：http://192.168.0.195:5000/app/payment/object_recent_viewed/grid/all
- 我对比了下，发现返回`record: {o: "qhd_informations", ids: ["XZM4ytvu4L9LQ8TQx"]}`这种格式的是因为数据库中没有查到对应的id值的记录，这应该是删除数据的时候没有同步把最近查看数据删除
![image](https://user-images.githubusercontent.com/6219465/67478359-7af24f00-f68e-11e9-80b0-e2194f460614.png)

**Comment by sunhaolin** [comment]
经测试未发现会导致bug或者其他问题
