### ISSUE TITLE
子表 master_detail 字段类型新增属性 sharing

### ISSUE THREAD

**Issue by hotlong** [steedos/creator#1461]
```
sharing: masterRead / masterWrite
```
- [x]  masterRead: 当主表只读时，就能增删改子表。
- [x] masterWrite: 当主表可以修改时，才能增删改子表。(默认值)
- [x] 新增和修改子表记录中的master_detial字段时需要根据sharing校验是否有权限新增和修改
- [x] 服务端触发器：当detail表新增和修改的时候，detail.owner=master.owner
- [x] 服务启动时校验，每个表只能有一个master_detail类型字段

**Comment by sunhaolin** [comment]
废弃字段上的sharing属性，调整为write_requires_master_read 【boolean】
https://github.com/steedos/steedos-platform/issues/1130
