### ISSUE TITLE
台账关联附件无法新增

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/creator#1501]
![image](https://user-images.githubusercontent.com/26241897/71304189-28b77b00-23fe-11ea-9d98-42f1d7d20dd2.png)

**Comment by lizhenghotoa** [comment]
![image](https://user-images.githubusercontent.com/26241897/71304328-10e0f680-2400-11ea-8f8b-a5553fdb7ce6.png)

**Comment by yinlianghui** [comment]
权限问题单独报bug了
