### ISSUE TITLE
二维表问题汇总

### ISSUE THREAD

**Issue by hotlong** [steedos/creator#1518]
- “字段”配置了“签约对象.名称”，在下钻数据列表中此列显示为空。
- 下钻列表太小，缩在中间。
- 如果配置了 name 字段可以考虑加上链接，弹出窗口到对应的记录

![image](https://user-images.githubusercontent.com/50353452/71392300-84724600-2642-11ea-85e1-9c8b74995cf8.png)

**Comment by yinlianghui** [comment]
增加优化清单：
-下钻列表header部分要支持下拖动改变宽度
-下钻列表列太多时底部应该显示水平滚动条
-下钻列表标题为什么显示为”总下钻数据"

**Comment by yinlianghui** [comment]
> 增加优化清单：
> -下钻列表header部分要支持下拖动改变宽度
> -下钻列表列太多时底部应该显示水平滚动条
> -下钻列表标题为什么显示为”总下钻数据"

以上都处理了最后一条指的是grid列表底下最后一行总计中每个单元格点开的都是带“总”前缀的，它之前的行都会带上二维表的行标题作为前缀
