### ISSUE TITLE
手机客户端界面问题

### ISSUE THREAD

**Issue by hotlong** [steedos/creator#1565]
原因是 http://http1921680515000.meteor.local/assets/icons/ 文件夹不存在

![image](https://user-images.githubusercontent.com/50353452/72041133-ad9f0180-32e5-11ea-9917-d18ddccf76e1.png)
![image](https://user-images.githubusercontent.com/50353452/72041150-b1cb1f00-32e5-11ea-9a56-8d36a8a7e096.png)

**Comment by hotlong** [comment]
手机客户端访问 notifications 接口失败

![image](https://user-images.githubusercontent.com/50353452/72042197-adeccc00-32e8-11ea-8e87-2080694376c8.png)

**Comment by baozhoutao** [comment]
5663532

**Comment by baozhoutao** [comment]
- [ ] 企业logo显示异常
- [ ] 左侧的链接，应该是相对路径
- [ ] 第一次登录也会跳转到原服务器

**Comment by baozhoutao** [comment]
点击通知消息会跳转到 root url

**Comment by baozhoutao** [comment]
- [ ] 手机版：/assets/images/illustrations/empty-state-no-results.svg 加载失败 
- [ ] 手机IOS版：点击 收藏，通知记录后，dropdown列表未自动关闭

**Comment by baozhoutao** [comment]
- [ ] 进入一次404页面后，无法通过通知，收藏记录 进入其他数据的详细页面

**Comment by baozhoutao** [comment]
- [ ] 服务地址有ROOT_URL_PATH_PREFIX 时，icon显示异常
