### ISSUE TITLE
流程图不支持有 ROOT_URL_PATH_PREFIX的情况

### ISSUE THREAD

**Issue by baozhoutao** [steedos/creator#1649]

**Comment by yinlianghui** [comment]
- 原版的流程图URL作废：`/packages/steedos_workflow-chart/assets/index.html?instance_id=...`
- 新版本流程图URL：`/api/workflow/chart/traces?instance_id=...`
- 已经修正申请单详细界面`流程图`打开的URL地址了
- 新版本流程图在PC上华信客户端、审批王客户端测试通过了，没发现什么问题
- 新版本流程图在手机上审批王客户端也测试通过了，没发现什么问题
