### ISSUE TITLE
e.registerDashboardComponent is not a function

### ISSUE THREAD

**Issue by baozhoutao** [steedos/creator#1729]
![image](https://user-images.githubusercontent.com/6194462/79033238-38421600-7bdf-11ea-9971-5687d4eb50dc.png)

**Comment by yinlianghui** [comment]
apps\contracts项目报错，是因为creator未发包造成的，现在apps/contracts引用的webapp包是creator中的版本，我把调用的地方去掉提交了，现在不会报错了
