### ISSUE TITLE
master_detail和lookup类型字段，支持配置过滤器和按指定字段排序。

### ISSUE THREAD

**Issue by liminglang** [steedos/creator#178]
如，在档案里使用保管期限(关联到archive_retention表），在新增或编辑档案的保管期限时，按永久->长期->短期->30年->10年->4年的顺序显示。

**Comment by baozhoutao** [comment]
field通过设置：reference_sort来指定排序规则， eg: `reference_sort: {years: -1}`

**Comment by baozhoutao** [comment]
filters 配置示例：`filters: [["years", "$gt", 10]]`
