### ISSUE TITLE
项目运行环境升级至node12

### ISSUE THREAD

**Issue by sunhaolin** [steedos/creator#1785]

**Comment by baozhoutao** [comment]
create-steedos-app 项目也需要调整， 目前限制了node版本必须为>=10

**Comment by sunhaolin** [comment]
主要改动 是 依赖的fibers包版本从^3.1.1升为^4.0.0

**Comment by sunhaolin** [comment]
create-steedos-app 项目 已调整 60a92257ef2ba176304645a3d5dfd659e6b04e00

**Comment by sunhaolin** [comment]
切换node版本后，执行yarn --force重新安装包，因为有的包要重新编译
