### ISSUE TITLE
源码跑服务，发现合同对象的company_id字段定义了label为"我方单位"，但是却显示成了"分部"

### ISSUE THREAD

**Issue by yinlianghui** [steedos/creator#1803]
应该是被`base.zh-CN.i18n.yml`中字义的base_field_company_id给覆盖了。
![image](https://user-images.githubusercontent.com/6219465/83599152-0d03f380-a59e-11ea-989b-592765405d19.png)

**Comment by hotlong** [comment]
base 翻译问题，重复
