### ISSUE TITLE
顶部bar提供个性化定制样式功能，实现类似trqgw项目需求只要配置就能个性化界面

### ISSUE THREAD

**Issue by yinlianghui** [steedos/creator#1811]
- trqgw相关任务：[按设计要求，实现新的门户界面 #98](https://github.com/steedos/steedos-project-trqgw/issues/98)
- 拟可能增加以下配置功能
    - 允许上传定义整个bar背影图片
    - 允许定义整个bar的前景色是否反色，默认不反色
    - 允许定义是否显示全局搜索框
- 同类需求可以一起处理，见任务：[左上角Logo不要限制方形；是否显示工作区名称可以加一个开关 #362](https://github.com/steedos/steedos-platform/issues/362)

**Comment by hotlong** [comment]
项目中通过样式定义就可以，不作为标准功能
