### ISSUE TITLE
按照 odata 协议实现object增删改查操作，并对照编写API文档

### ISSUE THREAD

**Issue by steedos** [steedos/creator#185]
参考：
- [使用 OData 终结点的 OData 系统查询选项](https://msdn.microsoft.com/zh-cn/library/gg309461(v=crm.7).aspx)
- [使用 OData 终结点执行基本数据操作](https://msdn.microsoft.com/zh-cn/library/gg328090(v=crm.7).aspx#BKMK_RetrievingRecordsJSON)
- [OData endpoint Http status codes](https://msdn.microsoft.com/zh-cn/library/gg334391(v=crm.7).aspx)
- http://www.odata.org/getting-started/basic-tutorial/

**Comment by zonglu233** [comment]
odata的增删改查每个接口对应一个帮助文档，并根据帮助文档进行测试。
