### ISSUE TITLE
信息上报近期问题汇总

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/creator#192]
1、点击 报送的信息详情后，返回上一步 信息列表页面 不方便。
2、目前信息列表界面每页显示20条信息，希望修改成每页显示10条信息。
3、信息报送数据导出，列表内容是按照固定排序还是按得分多少排序？排序还需要调整，建议按固定好的单位排序，或者按分数从高到低排序；提出没有报送信息的单位也应该显示在报表报送单位字段上。
（杨帅还是希望能够按照部室、基层单位的顺序实现排序，以及未报送信息的单位也应该显示在报表上）
已经和杨帅说明以上几项功能开发起来可能有些难度，时间上可以延伸至下个月。
4、目前在 大字体 情况下，页面没有 横向滚动条。（处理中）
5、报送信息标题显示不全，有时会以 ... 来省略。（待更新）
6、目前信息列表界面没办法通过拖拽来调整信息列表的列宽。（处理中）

**Comment by chenzhipei** [comment]
没有报送信息的单位也应该显示在报表报送单位字段上

**Comment by marchtian** [comment]
遗留问题：
1、点击 报送的信息详情后，返回上一步 信息列表页面 不方便。

3、信息报送数据导出，列表内容是按照固定排序还是按得分多少排序？排序还需要调整，建议按固定好的单位排序，或者按分数从高到低排序；提出没有报送信息的单位也应该显示在报表报送单位字段上。
