### ISSUE TITLE
必填字段设置了默认值情况下，新建记录时，如果用户把默认值清除掉再保存，未提示必填

### ISSUE THREAD

**Issue by zhusijia** [steedos/creator#224]
测试到现象：
1. 字段未设置defaultValue属性时，编辑/新建记录时都没有问题
2. 字段有设置defaultValue属性时，编辑记录时没有问题，但是新建记录时，如果把默认值清除掉，会有问题（未提示必填）

> 其实第2点新建记录时的bug不是select字段特有的，普通字段都是有这个问题的。

### 总结：
- 该问题只在新建记录时用户手动清除了默认值才有问题，感觉不严重
- 该问题是AutoForm内核代码bug，且代码不在本地，不好处理，建议可以不处理

### 调式结果：
- AutoForm.validateForm函数有bug造成该问题，该函数源码不在我们项目本地，需要搞到本地后改，不好处理

- AutoForm.validateForm("creatorAddForm")/AutoForm.validateForm("creatorEditForm")结果为true，说明是这个AutoForm控件中这个函数的bug
![image](https://user-images.githubusercontent.com/6219465/52892986-dfd9d900-31d2-11e9-9788-745711933540.png)

- AutoForm.validateForm内部没有用AutoForm.getFormValues取值校验，而是用的AutoForm.getCurrentDataForForm，这个函数会把默认值加上再校验，所以才出问题了
![image](https://user-images.githubusercontent.com/6219465/52892971-ab661d00-31d2-11e9-8821-8349877010fd.png)

**Comment by yinlianghui** [comment]
未测试到问题
