### ISSUE TITLE
odata 接口支持跨space查询数据

### ISSUE THREAD

**Issue by steedos** [steedos/creator#233]
只有云管理员可以执行相关操作
- spaceId=common
- 权限判断时检查 user.is_cloudadmin = true
- 只能只读查询，增删改接口不可用
- is_cloudadmin选择工作区时，多一个common选项

**Comment by baozhoutao** [comment]
数据库脚本：
#添加Common工作区
var cloudamin = db.users.findOne({is_cloudadmin:true})

db.spaces.insert({_id:"common",name:"Common",is_paid: true, is_deleted: false, balance: 10000000, enable_register: false, "modules": [ 
        "workflow.professional", 
        "workflow.standard", 
        "workflow.enterprise"
    ], owner: cloudamin._id, admins: [cloudamin._id]})

db.space_users.insert({
    "_id" : "common_" + cloudamin._id,
    "name" : cloudamin.name,
    "email" : cloudamin.emails[0],
    "space" : "common",
    "user" : cloudamin._id,
    "user_accepted" : true,
    "manager" : cloudamin._id,
})
