### ISSUE TITLE
objects字段属性readonly为true时，defaultValue设置的值无效。

### ISSUE THREAD

**Issue by zonglu233** [steedos/creator#250]
![image](https://user-images.githubusercontent.com/23066347/37817239-1ee0c21a-2eb1-11e8-8959-2cd2d576b7bc.png)

**Comment by steedos** [comment]
问题出在 disabled 属性上，保存时不会提交。

**Comment by liminglang** [comment]
对于只读的字段，使用两个field控制，其中一个隐藏了，界面上显示的这个也只是用一个labe把它显示出来，不需要阴影和input框。
