### ISSUE TITLE
注册新企业，成功后一直loading，但是刷新后可以登录

### ISSUE THREAD

**Issue by yinlianghui** [steedos/creator#278]
@liminglang 请先测试确认下是不是发送邮件失败造成的。

**Comment by lizhenghotoa** [comment]
1、cn上是可以正常注册跳转到首页， 且能够成功发送验证邮件的。
2、apps更新master最新代码后 ，注册后跳转到首页加载一片空白(首页的门户脚本有问题)，其他模块正常。且邮箱没有收到注册邮件。
<img width="960" alt="_15234125262564" src="https://user-images.githubusercontent.com/26241897/38593328-6e5169d2-3d73-11e8-9c17-be562270c011.png">
3、creator更新master最新代码后，注册后跳转的界面只有背景图。
<img width="960" alt="_15234132385676" src="https://user-images.githubusercontent.com/26241897/38593352-7ee21ddc-3d73-11e8-9218-c5f63e802f1f.png">

**Comment by yinlianghui** [comment]
已解决，原因是后台会报错，现在本地只会因为邮件而一直loading了，CN打包后应该没问题

**Comment by yinlianghui** [comment]
测试要点：
1.之前注册成功后就算刷新进入系统后也是一片空白，原因是后台报错造成注册失败(没有增加space_user数据)，需要测试注册成功后刷新是否能正常登录使用系统。
2.在1的基础上应该只剩下发邮件造成一直loading的问题了，本地配置好邮件后，用真实邮件注册试下看看是否不会再有一直loading的问题。

**Comment by lizhenghotoa** [comment]
creator项目在未配置邮件服务的情况下，不能正常跳转，一直显示加载状态，但是账号已注册成功。
在配置好邮件服务后，apps项目和creator项目注册后都能正常自动跳转进入系统。
