### ISSUE TITLE
主表/相关表类型的字段，新建后在列表界面中不显示该字段的信息。

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/creator#287]
<img width="960" alt="3ad2c60b18fb21c264dfe071c091391" src="https://user-images.githubusercontent.com/26241897/38255563-b511822a-378e-11e8-9b0c-78afd9e7d59d.png">
<img width="960" alt="f292ba0b731767a8247e0f715b11f89" src="https://user-images.githubusercontent.com/26241897/38255583-c06c02bc-378e-11e8-8461-fd9d36bb7ad6.png">

**Comment by steedos** [comment]
不能重现
