### ISSUE TITLE
软件包 packages

### ISSUE THREAD

**Issue by steedos** [steedos/creator#296]
- 开发人员可以创建软件包；
- 软件包可以选择数据库、代码中创建的：应用、自定义对象，以及对象相关列表视图、admin、user的对象权限、报表、脚本等信息；
- 软件包可导出json；
- 导出的json可安装到另一个工作区或是另一个系统中；

**Comment by baozhoutao** [comment]
导出、导入支持以下对象：
- 应用
- 对象
- 列表视图
- 权限组
- 权限集
- 报表

**Comment by baozhoutao** [comment]
导入校验规则如下：
- 应用：如果导入的应用已通过代码定义过，则不允许导入
- 对象：对象名称不允许重复；只有企业版支持配置服务器端触发器
- 应用中引用的对象必须都存在
- 列表视图：列表视图中定义的对象必须存在
- 权限组：同一个工作区中的权限组名称不允许重复；权限组中授权下的应用必须都存在
- 权限集：权限集中指定的object必须存在；对应权限组必须存在
- 报表：对象必须存在

**Comment by baozhoutao** [comment]
测试：
- [ ] 应用导入
- [ ] 对象导入
- [ ] 列表视图导入
- [ ] 权限组导入
- [ ] 权限集导入
- [ ] 报表导入
