### ISSUE TITLE
记录级权限

### ISSUE THREAD

**Issue by steedos** [steedos/creator#297]
共享规则 permission_share
- 字段： object_name, filters,  organizations， users， permissions("r"/"w")
- 对象可配置共享规则，满足规则的记录，自动设置 share_organizations， share_users 的值

每个表新增数组类型字段sharing，数组中内嵌文档，用于保存每一条记录的共享信息
```
"sharing": [
	{
		"u": [user_id],  # 授权用户
		"o": [organization_id] # 授权组织
		"p": "r"/"w"    # 访问权限 read / write
		"r": rule_id    # 如果由规则生成，记录对应的id，便于重新计算，如果为空，重算时不覆盖。
	}
]
```

每个表在新增和修改记录时
- 自动计算并保存 sharing 字段；

用户权限修改
- 如果当前用户有 readAll, modifyAll 权限，不需要做共享级别的权限检查
- 如果是记录的所有者，对象权限中配置的增删改权限可生效
- 如果属于记录的共享者范围，对象权限中配置的增删改权限可生效

参考 Salesforce 设计文档 https://resources.docs.salesforce.com/sfdc/pdf/salesforce_record_access_under_the_hood.pdf

**Comment by yinlianghui** [comment]
测试要点：
- [ ] 请对照文档【https://github.com/steedos/creator/blob/master/doc/%E6%9D%83%E9%99%90%E9%85%8D%E7%BD%AE%E7%9B%B8%E5%85%B3.md】中第7小节测试。
- [ ] 重点测试规则变更那块，无论规则怎么变更，都要保证老的规则失效，并且新规则生效了。
