### ISSUE TITLE
lookup 下拉框最下面加一个新建行，点击弹出modal新增一条相关对象的记录

### ISSUE THREAD

**Issue by steedos** [steedos/creator#326]
这个问题很棘手，需要在浏览器中同时弹出两个modal对象，但是我们目前modal的很多参数都是通过session变量控制的。

![image](https://user-images.githubusercontent.com/3104826/38599969-1144fdc2-3d95-11e8-9538-77379950d0e5.png)

**Comment by baozhoutao** [comment]
测试内容，测试modal的lookup字段必须有reference_to 属性，并且其值为String类型
- [ ] 测试lookup字段单选时
- [ ] 测试lookup字段多选时
- [ ] 测试lookup有optionsFunction属性时
