### ISSUE TITLE
提供给用户使用的odata标准函数

### ISSUE THREAD

**Issue by steedos** [steedos/creator#347]
操作服务端
- Creator.odata.get(object_name, id): 调用odata api，获取一条记录的内容
- Creator.odata.get(object_name, id, field_name): 调用odata api，获取一条记录的内容中某个字段的内容
- Creator.odata.query(object_name, filters, fields, sort): 调用odata api，获取列表数据
- Creator.odata.insert(object_name, doc) ：调用odata api，插入一条记录，返回odata返回内容
- Creator.odata.update(object_name, id, doc):  调用odata api，修改一条记录，返回odata返回内容
- Creator.odata.delete(object_name, id):  调用odata api，删除一条记录，返回odata返回内容

**Comment by liminglang** [comment]
Creator.odata.get(object_name, id, field_name),如果给的field_name是lookup型字段，那么返回什么？

**Comment by liminglang** [comment]
Creator.odata.query(object_name, filters, fields, sort)，传过来的参数是什么样的
