### ISSUE TITLE
对象、字段等信息修改后能否自动刷新界面

### ISSUE THREAD

**Issue by steedos** [steedos/creator#363]

**Comment by baozhoutao** [comment]
测试清单：
apps：
- [ ] 新建增一条app，用户打开 “应用程序启动器” 时，可以看到新建的app
- [ ] 修改app记录，修改app的objects或者其他属性，再不需要刷新的情况下就应该能看到最新的值
- [ ] 删除app记录，删除app后，界面不能报错
objects:
- [ ] 新增object记录，client端不刷新，应该能及时看到(需要将新object添加到app中)
- [ ] 修改object记录，比如字段、显示名称、图标等，应该实时生效
- [ ] 删除object后，界面不能报错
