### ISSUE TITLE
ODATA接口未能支持带$符号字段的搜索结果

### ISSUE THREAD

**Issue by yinlianghui** [steedos/creator#389]
报错信息：
![image](https://user-images.githubusercontent.com/6219465/39169357-14070bba-47ca-11e8-95e1-b668d6a3902a.png)
比如字段如下：
![image](https://user-images.githubusercontent.com/6219465/39169373-2303c252-47ca-11e8-856f-068bab42cf98.png)

**Comment by liminglang** [comment]
不支持带$符号的字段
