### ISSUE TITLE
为每个object的name字段自动建立索引

### ISSUE THREAD

**Issue by liminglang** [steedos/creator#393]
- 在服务端初始化fields的时候，自动把对应的index属性 设置为true
- try .. catch ，确保某个表中有错误数据不会导致服务停止运行
- schema中限定name字段的最大长度，确保将来不会有错误数据。

**Comment by steedos** [comment]
在服务端初始化fields的时候，自动把对应的indexable 设置为true

**Comment by steedos** [comment]
会出故障，暂停
