### ISSUE TITLE
ODATA改了记录的时候返回值不应该返回所有字段值吧，应该返回传入的$set字段，而且要有权限

### ISSUE THREAD

**Issue by yinlianghui** [steedos/creator#395]
![image](https://user-images.githubusercontent.com/6219465/39176713-0da73446-47e0-11e8-8d72-5972d193492f.png)

**Comment by steedos** [comment]
这个要确认odata的规范，但是只返回传入的值肯定不行。以为有些字段是在服务端生成的

**Comment by steedos** [comment]
这个事情不急，可以延后

**Comment by steedos** [comment]
8.2.8.7 Preference return=representation and return=minimal
The return=representation and return=minimal preferences are defined in [RFC7240].

In OData, return=representation or return=minimal is defined for use with a POST, PUT, or PATCH Data Modification Request other than to a stream property, or to an Action Request. Specifying a preference of return=representation or return=minimal in a GET or DELETE request, or any request to a stream property, SHOULD return a 4xx Client Error.

A preference of return=representation or return=minimal is allowed on an individual Data Modification Request or Action Request within a batch, subject to the same restrictions, but SHOULD return a 4xx Client Error if specified on the batch request itself.

A preference of return=minimal requests that the service invoke the request but does not return content in the response. The service MAY apply this preference by returning 204 No Content in which case it MAY include a Preference-Applied response header containing the return=minimal preference.

A preference of return=representation requests that the service invokes the request and returns the modified resource. The service MAY apply this preference by returning the representation of the successfully modified resource in the body of the response, formatted according to the rules specified for the requested format. In this case the service MAY include a Preference-Applied response header containing the return=representation preference.
