### ISSUE TITLE
同一个record发起多次审批

### ISSUE THREAD

**Issue by sunhaolin** [steedos/creator#403]
- record相关可以列出申请单列表，点击名称弹出窗口显示申请单（打印界面）
- 新增字段record.instances，去掉字段instance_ids和instance_state，当record.instances[0].state不为completed并且不为空时，record详细页`发起审批`不显示
- 当审批结束后，将record.instances([{_id: xxx, state: xxx}]) 信息更新， instances[0]表示最新审批单
- 在apps instance model里写after.update方法，当申请单状态为completed时插入同步队列
- instances字段record_ids:{o:object_name,ids:[]}，改为[{o:object_name,ids:[]}]数组用于记录对应的record信息

**Comment by lizhenghotoa** [comment]
同一审批发起两次不同流程的审批，第二次审批修改对应字段关系后，不会返回到record记录中。
