### ISSUE TITLE
af-modal窗口中只读字段样式问题

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/creator#413]
<img width="947" alt="00bfe6f34caf6745f493f998f19d294" src="https://user-images.githubusercontent.com/26241897/39346144-363f5488-4a1f-11e8-8d0d-1cf333192e44.png">
<img width="940" alt="b350a3248116d636a2ddb58f1532077" src="https://user-images.githubusercontent.com/26241897/39346150-3c21ace8-4a1f-11e8-9597-991ac751fdb9.png">

**Comment by lizhenghotoa** [comment]
所有字段类型都会出现这个问题。

**Comment by zhusijia** [comment]
添加下划线
