### ISSUE TITLE
日期类型，在列表视图上的时间跟编辑时的时间不一样

### ISSUE THREAD

**Issue by liminglang** [steedos/creator#440]
- 升级最新的 bootstrap-datetimejs包，并制作成包steedos:bootstrap3-datetimepicker
- 添加时间功能包risul:moment-timezone
- 为日期控件配置timezoneId属性：
```
if field.type == "date"
    fs.type = Date
    fs.autoform.afFieldInput =
        type: "bootstrap-datetimepicker"
        timezoneId: "utc"
        dateTimePickerOptions:
            format: "YYYY-MM-DD"
else if field.type == "datetime"
    fs.type = Date
    fs.autoform.afFieldInput =
        type: "bootstrap-datetimepicker"
        dateTimePickerOptions:
            format: "YYYY-MM-DD HH:mm"
```
- 所有只读，包括列表只读统一使用moment.utc(this.val).format('YYYY-MM-DD')显示值，需要进行utc(val)
- 手机端日期/日期时间控件优化成手机端原生控件效果

**Comment by yinlianghui** [comment]
测试要点：
- [ ] 请测试日期时间/日期控件是否能正常使用，包括保存及显示值。
- [ ] 请测试所有日期时间/日期字段的只读效果是否正常。
- [ ] 以上均需要考虑时区影响。
