### ISSUE TITLE
文书档案新建视图后，填写过滤条件后点击确定服务端报错。

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/creator#449]
![image](https://user-images.githubusercontent.com/26241897/39616465-11c956be-4fae-11e8-99b6-bf65ae1055e6.png)

**Comment by liminglang** [comment]
可以暂时不支持过滤器的值包含英文中括号、换行等特殊符号。

**Comment by lizhenghotoa** [comment]
![image](https://user-images.githubusercontent.com/26241897/39903109-1a7b7bba-5504-11e8-80a6-ef3935565502.png)
