### ISSUE TITLE
数据导入上传20MB的文件，页面报error 控制台报错

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/creator#455]
<img width="960" alt="_15256576184630" src="https://user-images.githubusercontent.com/26241897/39681293-d17d810e-51db-11e8-9da8-4f2d651b9a2b.png">

**Comment by yinlianghui** [comment]
- 现在右上角已能支持文件超大时提示了。
- 本地配置了nginx后，如果未配置请求文件大小才会出现文件超大时的提示，配置了合理的大小后就不会再有异常。
