### ISSUE TITLE
在server端可执行的脚本中，应该只能获取到我们指定的数据，比如Creator\db等都应该访问不到的

### ISSUE THREAD

**Issue by yinlianghui** [steedos/creator#488]
需要确认下，在服务端执行脚本的时候，是不是控制了可访问的变量，在脚本中能获取到数据库连接，那会出问题的。
尤其是全局变量，不然可以通过一个脚本就把我们数据库删掉的。
目前好像只有server端的trigger能执行服务端脚本。

**Comment by yinlianghui** [comment]
在服务端before.update.server打日志发现：
- db.drop,db.dropIndex,db.dropIndexes,db.ensureIndex等函数是不能调用的，直接是undefined。
- db.direct.remove,remove,direct.update,db.find，等是可以调用的，但是脚本是管理员操作，理论上也不存在安全问题

**Comment by baozhoutao** [comment]
目前server端的trigger是企业版才支持的，如果降低为标准版或者专业版，此问题必须处理掉。否则很简单的一条脚本就会把数据库、表删除掉
