### ISSUE TITLE
编辑相关流程界面，新增字段映射关系后会自动清空上一次映射关系记录。

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/creator#496]
<img width="960" alt="_15262694916041" src="https://user-images.githubusercontent.com/26241897/39977410-60674392-576c-11e8-9bb0-49d1d5f283eb.png">
<img width="960" alt="_15262693837524" src="https://user-images.githubusercontent.com/26241897/39977412-63771a62-576c-11e8-83e7-a5d39fdc1aec.png">

**Comment by lizhenghotoa** [comment]
表格字段目前不会出现清空上一条记录的情况

**Comment by baozhoutao** [comment]
选人、lookup控件都有此问题
