### ISSUE TITLE
creator 列表显示的时间和详细页显示的时间不一致

### ISSUE THREAD

**Issue by zonglu233** [steedos/creator#526]
关联的老任务：日期类型，在列表视图上的时间跟编辑时的时间不一样 #440
请按#440的测试要点重新测试

![image](https://user-images.githubusercontent.com/23066347/42357076-9b282b3e-8108-11e8-8c5b-4a62f653bde3.png)

![image](https://user-images.githubusercontent.com/23066347/42357067-92c22ef4-8108-11e8-83d8-d2146e2059a9.png)

**Comment by yinlianghui** [comment]
关联的老任务：日期类型，在列表视图上的时间跟编辑时的时间不一样 #440
