### ISSUE TITLE
使用devexpress源码后，‘’加载中‘’和‘’没有可显示的项目‘’样式错乱

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/creator#539]
![image](https://user-images.githubusercontent.com/26241897/42610383-e0d481fe-85c3-11e8-927c-ae916b05158c.png)
![image](https://user-images.githubusercontent.com/26241897/42610396-f9b0c336-85c3-11e8-9b7a-4561493ce6cc.png)

**Comment by yinlianghui** [comment]
devexpress源码升级后列表样式滚动条等有问题 #543
