### ISSUE TITLE
ODATA接口当查询条件不对时，会返回所有记录

### ISSUE THREAD

**Issue by yinlianghui** [steedos/creator#546]
![image](https://user-images.githubusercontent.com/6219465/42678203-c3e31090-86b0-11e8-9cec-e1839d59dd0a.png)

上面的请求，估计是因为没加引号，加引号应该能找到正确的记录，但是条件错误的时候，应该返回空值，而不是所有记录

**Comment by liminglang** [comment]
odata接口使用第三方解析包，对于这种情况暂不支持。
![_15317966465622](https://user-images.githubusercontent.com/27475169/42794405-2b13d530-89b1-11e8-976f-7e20abc4e4ec.png)

**Comment by liminglang** [comment]
按正确的格式写即可，$filter: `from eq '${userId}' and space eq '${this.space_id}'`
