### ISSUE TITLE
从会议室界面点击会议，会报错

### ISSUE THREAD

**Issue by chenzhipei** [steedos/creator#555]
![image](https://user-images.githubusercontent.com/15027092/42990775-43f3323a-8c36-11e8-8979-5f11a76d4561.png)

**Comment by liminglang** [comment]
重现方式：1.在A对象下配置一个sortable类型的字段，列表视图中也包含这个字段
2.在界面上使用该字段排序，然后在界面上会出现一个向上/下的箭头
3.切换到其他视图上，出现该错误。

**Comment by liminglang** [comment]
处理方案：选择列表视图上的排序字段，选择清除排序，在切换到其他对象上，再切换回来则不报错。
