### ISSUE TITLE
有排序字段的对象，切换到其他对象，在切换回来会报错。

### ISSUE THREAD

**Issue by liminglang** [steedos/creator#563]
重现方式：
1.在A对象下配置一个sortable类型的字段，列表视图中也包含这个字段
2.在界面上使用该字段排序，然后在界面上会出现一个向上/下的箭头
3.切换到其他对象上，出现该错误。

**Comment by yinlianghui** [comment]
![image](https://user-images.githubusercontent.com/6219465/45462308-d935ca00-b739-11e8-90b5-7958eb40ff4a.png)

**Comment by yinlianghui** [comment]
这个报错没有实质影响，可以忽略
