### ISSUE TITLE
文件历史版本不显示

### ISSUE THREAD

**Issue by zonglu666** [steedos/creator#585]
![image](https://user-images.githubusercontent.com/23066347/44519046-746cee00-a6fe-11e8-8624-48899f1718b7.png)
![image](https://user-images.githubusercontent.com/23066347/44519056-7b93fc00-a6fe-11e8-8529-46611e3083b4.png)

**Comment by yinlianghui** [comment]
暂时文件版本只能显示上传时间字段，其他比如名称、文件大小、上传者都是内嵌字段，未找到显示内嵌字段的解决办法
