### ISSUE TITLE
creator前台拖动字段宽度或调整字段顺序后，不能自动保存

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/creator#594]
- 字段宽度或次序调整后到保存成功会需要总共2秒左右时间，包括请求后台保存时间及前端控件本身需要准备的时间在内，期间如果点击其他链接离开了当前列表界面就会保存失败或没有保存。
- 如果在其中增加全局的loading效果过虑，体验又会很差

> 只调整字段顺序有额外的bug，如果只调整字段顺序而不调整宽度的话，点击其他界面再回来之前的顺序就会还原
1. 其实保存成功了，只是重新进入当前列表界面时，取的是之前本地订阅的老的数据，并且重新把老数据自动保存到数据库了。
2. 根本原因是保存数据后，本地虽然重新订阅了相关数据，但是没有订阅到宽度及顺序内容数据。
3. 造成第2条的原因是宽度及顺序内容数据表结构有问题，用的是object的key-value形式来保存各个字段的次序，而不是数组形式（格式如下），这样当次序变化时，meteor订阅器其实是认为数据没有变化的，所以不会重新订阅到column_width相关数据。
![image](https://user-images.githubusercontent.com/6219465/45476307-3731d400-b771-11e8-866a-9d5e77d9cb3c.png)

**Comment by yinlianghui** [comment]
测试要点：
- [ ] 上述只调整字段顺序有额外的bug问题已解决。
- [ ] 无论改变字段次序还是宽度，如果等待2秒左右后，相关结果保存成功
