### ISSUE TITLE
Error: TypeError: Cannot read property 'avatars' of undefined

### ISSUE THREAD

**Issue by steedos** [steedos/creator#655]
http://127.0.0.1:3000/api/files/avatars/mFxKDj6AD9gNByNyc

Error in method "/api/files/:value/:value/", Error: TypeError: Cannot read property 'avatars' of undefined
    at Object.httpGetHandler (packages\steedos_cfs-access-point.js:372:33)
    at Object.get (packages\steedos_cfs-access-point.js:714:39)
    at packages\steedos_cfs-http-methods.js:604:33

**Comment by baozhoutao** [comment]
问题原因是:数据缺少copies属性, 可能是附件上传失败导致
