### ISSUE TITLE
从文件详细界面点击浏览器左上角返回按钮会报错

### ISSUE THREAD

**Issue by yinlianghui** [steedos/creator#662]
重现规则：
- 从商品详细界面点击相关中的文件，进入文件详细界面，这时再点击左上角返回按钮会报错。
- 规则是只要从某个详细界面的相关中进入另一个详细界面，如果两个详细界面都存在“相关”列表的话，点击左上角返回按钮会报错并且界面异常。

调式结果及解决办法：
- 是因为详细界面都调用到grid列表template，在这个grid中是根据转入的related_object_name来请求相关列表数据的，但是它同时又直接监听了Session中object_name，record_id等变量的变化来请求列表数据，这两种方式冲突了，所以会报错。
- 当上述两种方式冲突时，grid会先响应session的变化来请求数据，这时模板传入的related_object_name参数还没有变化，造成“相关”列表请求数据用的是老的“related_object_name参数”数据
- 可能把grid中直接监听Session中object_name，record_id等变量的方式改为统一由调用template时传参的方式，即只监听参数变化，不直接监听Session中的变量变化，能解决该问题。
> 因改动比较大，而且是由点击浏览器左上角返回按钮才会出现这个bug，所以暂定不处理。

![image](https://user-images.githubusercontent.com/6219465/47841710-7eddef00-ddf5-11e8-8df1-ae2f0235714e.png)
![image](https://user-images.githubusercontent.com/6219465/47762889-5d97d880-dcf9-11e8-9b27-6edeffbe92f1.png)

**Comment by yinlianghui** [comment]
![image](https://user-images.githubusercontent.com/6219465/47842591-17756e80-ddf8-11e8-974d-b3e3bafb730a.png)

**Comment by steedos** [comment]
已改为弹出窗口
