### ISSUE TITLE
组织结构连qhd数据库，不应该默认展开所有节点

### ISSUE THREAD

**Issue by steedos** [steedos/creator#672]
- [x] 改为：默认展开第一个节点，而不展开全部节点
- [x] 直接加载整颗树结构，而不是展开结点加载数据
- [x] 完全去掉了翻页功能

1. 后面尝试过展开节点时动态加载节点数据，没有成功
2. 排序跟选人控件中的组织机构次序不一样，已修正多个排序字段的排序优先级bug
3. 中文排序问题另报了bug

**Comment by yinlianghui** [comment]
1. 后面尝试过展开节点时动态加载节点数据，没有成功
2. 排序跟选人控件中的组织机构次序不一样，未能找到解决方法
