### ISSUE TITLE
选人控件，第一个根节点列出所属单位

### ISSUE THREAD

**Issue by steedos** [steedos/creator#692]
- 如果当前space_user有所属单位且所属单位非根组织，第一个根节点列出所属单位
- 不需要列出主部门
- 如果 所属单位就是根节点，不要重复

**Comment by yinlianghui** [comment]
选人选组控件统一改成了：如果有所属单位则不显示主部门，只显示所属单位作为根节点，反之显示主部门及整个组织架构
