### ISSUE TITLE
sogo 用户同步

### ISSUE THREAD

**Issue by steedos** [steedos/creator#706]
将steedos用户同步到iredmail 和 sogo，并设置以下初始化参数。
![image](https://user-images.githubusercontent.com/3104826/48681984-f925b600-ebe0-11e8-9d9c-b70ad82040c9.png)

**Comment by marchtian** [comment]
sogo.public.sogo_user_profile.c_defaults
"SOGoMailComposeWindow": "inline",
"SOGoMailDisplayRemoteInlineImages": "always", 
"SOGoMailMessageForwarding": "inline"

**Comment by marchtian** [comment]
（1）vmail库增2条记录
INSERT INTO "public"."mailbox" ("username", "password", "name", "language", "storagebasedirectory", "storagenode", "maildir", "quota", "domain", "transport", "department", "rank", "employeeid", "isadmin", "isglobaladmin", "enablesmtp", "enablesmtpsecured", "enablepop3", "enablepop3secured", "enablepop3tls", "enableimap", "enableimapsecured", "enableimaptls", "enabledeliver", "enablelda", "enablemanagesieve", "enablemanagesievesecured", "enablesieve", "enablesievesecured", "enablesievetls", "enableinternal", "enabledoveadm", "enablelib-storage", "enableindexer-worker", "enablelmtp", "enabledsync", "enablesogo", "allow_nets", "lastlogindate", "lastloginipv4", "lastloginprotocol", "disclaimer", "allowedsenders", "rejectedsenders", "allowedrecipients", "rejectedrecipients", "settings", "passwordlastchange", "created", "modified", "expired", "active") VALUES ('test4@czpmail.com', '{SSHA512}f/JvElqpEwhm0cD+LYs2vlcy1DxI7ZGKV8TnDoVAX5t3PMLPhJ528BX3oeR6Bl7kFq5j2BBd1zk1zwwdGPHlB5pH4aCxvzDe', '', '', '/var/vmail', 'vmail1', 'czpmail.com/t/e/s/test4-2018.11.20.14.58.00/', '100', 'czpmail.com', '', '', 'normal', '', '0', '0', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', NULL, '1970-01-01 00:00:00', '0.0.0.0', '                                                                                                                                                                                                                                                               ', '', '', '', '', '', '', '1970-01-01 00:00:00', '2018-11-20 07:58:00', '2018-11-20 07:58:00', '9999-12-31 00:00:00', '1');

INSERT INTO "public"."forwardings" ("address", "forwarding", "domain", "dest_domain", "is_maillist", "is_list", "is_forwarding", "is_alias", "active") VALUES ('test2@czpmail.com
', 'test4@czpmail.com
', 'czpmail.com', '', '0', '0', '1', '0', '1');

（2）sogo库增1条记录
INSERT INTO "public"."sogo_user_profile" ("c_uid", "c_defaults", "c_settings") VALUES ('test4@czpmail.com', '{"SOGoMailReceiptNonRecipientAction": "ignore", "SOGoMailAutoSave": 5, "SOGoMailLabelsColors": {"$mdnsent": ["Return Receipt Sent", "#006600"], "$label5": ["稍后", "#993399"], "$label2": ["工作", "#FF9900"], "$label4": ["待办", "#3333FF"], "$label1": ["重要", "#FF0000"], "$label3": ["个人", "#009900"]}, "SOGoTimeFormat": "%H:%M", "SOGoAppointmentSendEMailNotifications": 1, "SOGoMailAddOutgoingAddresses": 0, "SOGoCalendarCategories": ["旅游", "竞争对手", "供应商", "其他", "会议", "结婚纪念日", "礼物", "电话", "客户", "公众假日", "项目", "假期", "工作", "想法", "追踪", "课题", "生日", "状态", "个人", "收藏夹", "休假"], "SOGoCalendarDefaultReminder": "NONE", "SOGoCalendarCategoriesColors": {"竞争对手": "#002661", "旅游": "#9708CC", "其他": "#3677FF", "供应商": "#8C1BAB", "会议": "#0396FF", "结婚纪念日": "#F6416C", "礼物": "#F55555", "电话": "#736EFE", "客户": "#9F44D3", "公众假日": "#28C76F", "项目": "#32CCBC", "假期": "#E96D71", "工作": "#F8D800", "想法": "#EA5455", "追踪": "#6018DC", "课题": "#E80505", "生日": "#DE4313", "收藏夹": "#623AA2", "个人": "#7367F0", "状态": "#0E197D", "休假": "#D939CD"}, "SOGoMailReceiptOutsideDomainAction": "ignore", "SOGoRememberLastModule": 0, "SOGoMailReceiptAnyAction": "ignore", "SOGoLoginModule": "Mail", "Vacation": {"daysBetweenResponse": 7, "autoReplyEmailAddresses": ["test4@czpmail.com"], "endDate": 0, "startDate": 0}, "SOGoDayStartTime": "08:00", "SOGoCalendarWeekdays": ["SU", "MO", "TU", "WE", "TH", "FR", "SA"], "SOGoCalendarTasksDefaultClassification": "PUBLIC", "SOGoTimeZone": "America\/New_York", "SOGoMailReceiptAllow": "1", "SOGoRefreshViewCheck": "every_5_minutes", "SOGoLanguage": "ChineseChina", "SOGoAnimationMode": "normal", "LocaleCode": "zh_CN", "SOGoMailSignaturePlacement": "below", "SOGoSelectedAddressBook": "collected", "SOGoMailComposeWindow": "inline", "SOGoContactsCategories": ["同事，竞争对手，客户，朋友，家庭，工作伙伴，服务商，媒体，VIP"], "SOGoFirstWeekOfYear": "January1", "SOGoShortDateFormat": "%d-%b-%y", "SOGoDefaultCalendar": "selected", "SOGoFirstDayOfWeek": 1, "SOGoCalendarEventsDefaultClassification": "PUBLIC", "SOGoMailComposeMessageType": "html", "SOGoLongDateFormat": "%A, %B %d, %Y", "SOGoMailDisplayRemoteInlineImages": "always", "AuxiliaryMailAccounts": [], "SOGoMailComposeFontSize": 0, "SOGoMailMessageForwarding": "inline", "SOGoMailShowSubscribedFoldersOnly": 0, "SOGoMailReplyPlacement": "below", "SOGoDayEndTime": "18:00", "locale": {"months": ["一月", "二月", "三月", "四月", "五月", "六月", "七月", "八月", "九月", "十月", "十一月", "十二月"], "shortMonths": ["一月", "二月", "三月", "四月", "五月", "六月", "七月", "八月", "九月", "十月", "十一月", "十二月"], "shortDays": ["星期日", "星期一", "星期二", "星期三", "星期四", "星期五", "星期六"], "days": ["星期日", "星期一", "星期二", "星期三", "星期四", "星期五", "星期六"]}}', '{"Calendar": {"PreventInvitationsWhitelist": {}}, "Contact": {}, "Mail": {}}');

备注：密码 是 123456
