### ISSUE TITLE
会议室每点击一次图片中位置的按钮, 就会重新加载所有的meeting记录

### ISSUE THREAD

**Issue by chenzhipei** [steedos/creator#764]
![image](https://user-images.githubusercontent.com/15027092/49564778-bfcea380-f95f-11e8-8524-e610848e3a7c.png)

**Comment by steedos** [comment]
支持开关 https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxScheduler/Configuration/#remoteFiltering

但是好想要调整odata接口。目前不能返回数据

**Comment by baozhoutao** [comment]
参考steedos-creator/client/views/calendarNew.coffee文件, dataSource中添加onLoading
