### ISSUE TITLE
【秦港合同】审计日志 - 字段历史

### ISSUE THREAD

**Issue by marchtian** [steedos/creator#779]
【需求】应对用户的每个关键操作进行记录，如登录、修改、删除等操作。同时,由协同办公系统归入的数据也要有相应的日志。

【方案】
- 对象新增开关 enable_audit
- 记录的创建时间和创建人，修改时间和修改人在记录中保存，点开可查看。（已实现）
- 系统登录日志。（另有单独任务）
- 对于enable_audit类型的对象，新增表audit_records，记录字段的修改历史。在odata接口修改接口中，保存字段的修改历史。
- 只有系统管理员可以在设置中查看 audit_records
- 对于enable_audit类型的对象，数据假删除。
- 工作流和台账的数据交互，记录在系统logs中，例如合同变更记录、合同执行（验收）记录等。
【权限】
- record 详细下的audit_records仅modifyAllRecords权限可见
【参考】
- 审计 https://help.salesforce.com/articleView?id=security_overview_auditing.htm&type=5
- 字段历史追踪 https://help.salesforce.com/articleView?id=tracking_field_history.htm&type=5
- 记录删除 https://help.salesforce.com/articleView?id=000199422&language=en_US&type=1

![image](https://user-images.githubusercontent.com/3104826/49713402-79d94e80-fc83-11e8-9ae7-c59273da0f92.png)

![image](https://user-images.githubusercontent.com/3104826/49713373-6332f780-fc83-11e8-94b3-b077e4da6b73.png)

**Comment by steedos** [comment]
字段修改历史应该单独设计一个表
