### ISSUE TITLE
【秦港合同】老合同管理台账的审批单存为附件

### ISSUE THREAD

**Issue by marchtian** [steedos/creator#786]
- 需要表单兼容chrome
- 适当优化样式，比如以前用textarea显示文本内容，可能导致显示不全。

建议先截图，提出具体优化方案和张工确认后再开发。

**Comment by baozhoutao** [comment]
方案为：以打印页面为基础，新建jsp文件， 在文件中修正合同表单模板中不兼容chrome的样式。新页面不需要登录
