### ISSUE TITLE
creator支持假删除功能

### ISSUE THREAD

**Issue by sunhaolin** [steedos/creator#794]
- 表添加开关enable_trash（boolean）表示是否开启假删除功能
- 表添加字段is_deleted（boolean），deleted (Datetime)， deleted_by
- odata查询接口只返回 is_deleted 为空的记录
- 删除时，设置 is_deleted = true

**Comment by marchtian** [comment]
> * 表添加字段is_deleted（boolean），deleted (Datetime)， deleted_by
因为base里已定义了这3个为默认字段，所以对象里无需再定义

> * odata查询接口只返回 is_deleted 为空的记录
“最近查看”里仍然 有 is_deleted 为true的记录
