### ISSUE TITLE
在creator中设置的图片签名，前台审批单中未显示图片

### ISSUE THREAD

**Issue by irenehy** [steedos/creator#797]
![image](https://user-images.githubusercontent.com/7665279/49721085-62f32600-fc9c-11e8-8cb1-c4d0208a0fe7.png)

**Comment by steedos** [comment]
估计是因为目前图片是保存在本地的，如果用云存储不会有问题。
但是本地安装版都有问题

**Comment by sunhaolin** [comment]
由于应用部署在linux系统中，故可以使用ln 建立虚拟目录将creator上传的附件存在apps中
如：
`ln -s /srv/workflow/cfs /srv/creator/cfs`
