### ISSUE TITLE
显示详情后，点击返回，应该返回至上次浏览到的页面（如在第三页打开一个记录查看，然后返回到第一页了）

### ISSUE THREAD

**Issue by liminglang** [steedos/creator#81]
1.应该有个时间限制，如在第三页打开一个记录，查看详情。应该设置一个时间值，如1个小时，一个小时内点击返回，则返回到第三页；超过1个小时点击返回，则返回到第一页。
2.按1中的例子，如果是1个小时内，查看详情后返回，是不是应该选中当前记录（在颜色上跟其他记录有所区别）

**Comment by steedos** [comment]
能不能做一个右键菜单，在新窗口打开？

**Comment by steedos** [comment]
以后计划开发左侧列表右侧详情的界面。
