### ISSUE TITLE
二级单位管理员问题汇总

### ISSUE THREAD

**Issue by steedos** [steedos/creator#820]
- [x] - 登录creator后没有自动进入第一个app
- [ ] - 登录apps后报404
- [x] - 点流程相关列表，当前视图显示为空，没有自动选中本单位

**Comment by baozhoutao** [comment]
登录creator后没有自动进入第一个app: 未能重现问题

**Comment by baozhoutao** [comment]
"登录apps后报404" 这个问题是由于连接的是抚顺石化的数据库, 代码用的是master的 没有启用steedos:portal模块导致的
