### ISSUE TITLE
 space_user  添加 organizations_parents 属性, 值为 space_users.organizations + organizations的parents

### ISSUE THREAD

**Issue by baozhoutao** [steedos/creator#827]
需要在以下数据库执行

- [ ] 秦皇岛
- [ ] 抚顺石化
- [ ] CN

**Comment by baozhoutao** [comment]
`
db.space_users.find({}, {_id: 1, organizations: 1}).forEach(function(su){
    orgs = db.organizations.find({_id: {$in: su.organizations}}, {parents: 1})
    organizations_parents = su.organizations || []
    orgs.forEach(function(org){
        org_parents = org.parents || []
        org_parents.forEach(function(parent_id){
            if(organizations_parents.indexOf(parent_id) < 0){
                organizations_parents.push(parent_id)
            }
        })
    })
    db.space_users.update({_id: su._id}, {$set: {organizations_parents: organizations_parents}})
})
`

**Comment by baozhoutao** [comment]
```
db.space_users.find({}, {_id: 1, organizations: 1}).forEach(function(su){
    orgs = db.organizations.find({_id: {$in: su.organizations}}, {parents: 1})
    organizations_parents = su.organizations || []
    orgs.forEach(function(org){
        org_parents = org.parents || []
        org_parents.forEach(function(parent_id){
            if(organizations_parents.indexOf(parent_id) < 0){
                organizations_parents.push(parent_id)
            }
        })
    })
    db.space_users.update({_id: su._id}, {$set: {organizations_parents: organizations_parents}})
})
```

**Comment by baozhoutao** [comment]
此脚本需要执行的数据库为:
- [ ] 秦皇岛
- [ ] 抚顺石化
- [ ] CN

**Comment by yinlianghui** [comment]
相关脚本也迁移到migrage脚本中了，对应脚本文件：`1568706515324-space_users-organizations_parents.js`
