### ISSUE TITLE
apps 设置功能都迁移到creator

### ISSUE THREAD

**Issue by steedos** [steedos/creator#838]
- apps配置参数 CREATOR_ROOT_URL
- 点设置跳转到creator
- 现有的设置全部在creator中实现菜单
  - 企业信息
  - 统计分析
  - 通讯录权限
  - API Token（建议作废）
  - 流程编号规则
  - 个人工作平台相关设置
  - 关于

关联：apps中组织机构功能迁移到creator中 #847 
关联：财务升级功能报错AraleQRCode is not defined #890

**Comment by yinlianghui** [comment]
参数配置的是settings.json的Meteor.settings.public?.webservices?.creator，如图：
![image](https://user-images.githubusercontent.com/6219465/50429678-d29f1d00-08fa-11e9-8d7c-98ff8f6e83ba.png)

url支持http/https的绝对路径，也支持/creator这样的相对路径
