### ISSUE TITLE
当前登录用户的userid与owner字段不一致，则无法显示作者。

### ISSUE THREAD

**Issue by zonglu233** [steedos/creator#85]
![_15157450371743](https://user-images.githubusercontent.com/23066347/34866011-f0383d3a-f7b5-11e7-8bcc-6ccdd9ce2c79.png)

![_15157450757988](https://user-images.githubusercontent.com/23066347/34866022-fac824e0-f7b5-11e7-8842-dcc95bbe20b0.png)

**Comment by steedos** [comment]
参考creator，用更复合的订阅格式。
