### ISSUE TITLE
creator中新建用户问题

### ISSUE THREAD

**Issue by yinlianghui** [steedos/creator#860]
1. 邀请老用户可以正常加入新工作区，而且在creator中可以正常登录使用
2. 邀请老用户后，老用户可以在apps中收到弹框邀请提示，但是creator中不会弹出这个提示框
3. creator中可以正常新建新用户，修正后也能正常发邮件激活用户设置密码了
4. creator中修改其他用户的手机号也测试过了，可以正常收到修改通知短信。
5. 发现短信模块，apps中引用的是steedos:smsqueue@0.0.2【已发布过该版本的meteor包】，creator引用的却是0.0.1版本的，我测试了下这个版本是可以正常收到短信通知的，所以没有升级到0.0.2.

弹框邀请提示指的是：
![image](https://user-images.githubusercontent.com/6219465/50417651-961fe280-0862-11e9-8dab-177744140313.png)

**Comment by sunhaolin** [comment]
由 [user, space_user 数据结构及功能调整 #44](https://github.com/steedos/steedos-accounts/issues/44) 重新设计
