### ISSUE TITLE
新建编辑人员时必填字段不填写时未提示报错

### ISSUE THREAD

**Issue by yinlianghui** [steedos/creator#885]
![image](https://user-images.githubusercontent.com/6219465/50537160-6a209c00-0b97-11e9-9b2c-85ae6dddec53.png)

**Comment by steedos** [comment]
是否lookup类型字段都有问题？

**Comment by baozhoutao** [comment]
此问题与lookup类型字段无关, 是对字段的属性配置有误. 规则: 有默认值的字段, 设置必填没意义
