### ISSUE TITLE
子表字段编辑时，也应按对象权限的定义出可选项

### ISSUE THREAD

**Issue by marchtian** [steedos/creator#923]
![image](https://user-images.githubusercontent.com/7553007/50876293-49620d00-1407-11e9-9ab9-d1fd83dfc5b9.png)

![image](https://user-images.githubusercontent.com/7553007/50876295-4ebf5780-1407-11e9-8fbb-802a4e5055aa.png)

**Comment by yinlianghui** [comment]
只需要把filter_by_company: true属性配置上就行了

**Comment by yinlianghui** [comment]
迁移到【公司级权限调整 #971】等相关任务
