### ISSUE TITLE
删除自定义对象生成的默认视图，比如all视图后报错

### ISSUE THREAD

**Issue by yinlianghui** [steedos/creator#964]
![image](https://user-images.githubusercontent.com/6219465/51223958-ec260880-197e-11e9-852b-5e3fa5d17818.png)

![image](https://user-images.githubusercontent.com/6219465/51224086-5e96e880-197f-11e9-9709-caaa3b64082b.png)

**Comment by steedos** [comment]
all 视图禁止删除
