### ISSUE TITLE
更新文档：定义相关lookup类型字段时，可为字段指定筛选条件。

### ISSUE THREAD

**Issue by yinlianghui** [steedos/creator#968]
![image](https://user-images.githubusercontent.com/6219465/51230601-82682780-199b-11e9-9b65-fba84bf66a31.png)

**Comment by baozhoutao** [comment]
见文档:https://github.com/steedos/creator/blob/master/packages/steedos-autoform-lookup/README.md

**Comment by yinlianghui** [comment]
功能未生效，先关掉，以后有需要再说
