### ISSUE TITLE
一个人属于多个单位的问题

### ISSUE THREAD

**Issue by steedos** [steedos/creator#978]
- [x] space_users 新增 company_ids 字段，记录 space_user.organizations 对应的 company_ids。(yin)
- [x] 服务端单位级权限， odata 数据过滤时，判断 in company_ids。(sun)
- [x] 客户端单位级权限，选择单位时，列出 company_ids 对应的单位。(yin)
- [x] organizations及space_uses这两个model关于company_id逻辑过一遍，新增company_ids逻辑。(yin)

**Comment by sunhaolin** [comment]
- 提供脚本设置space_user的company_ids
