### ISSUE TITLE
代码中定义的应用APP, 非管理员用户看不到

### ISSUE THREAD

**Issue by baozhoutao** [steedos/creator#979]
例如:
```
Creator.Apps.example =
		url: "/app/example"
		name: "Example"
		icon: "ion-ios-people-outline"
		icon_slds: "custom"
		visible:true
		is_creator:true
		objects: ["steedosLookupOdata"]
```

**Comment by yinlianghui** [comment]
经排查，是因为给user这个权限组设置了授权应用时，不会自动把visible为true的显示出来，而是会按这个授权应用设置的结果过滤出来，即如果给普通用户user这个权限组设置了授权应用时，应该普通用户能看到的全部加上，而不能只加一部分：
![image](https://user-images.githubusercontent.com/6219465/51361893-72238a00-1b0c-11e9-90a3-0f5c25c8f02c.png)
