### ISSUE TITLE
自动编号类型字段

### ISSUE THREAD

**Issue by steedos** [steedos/creator#98]
新增 自动编号 autonumber 字段类型。
- type:autonumber
- 可设定编号公式: {yyyy}-{mm}-{0000}

自动编号字段只读 

自动编号当前编号表 object_autonumber
- object_name:对象名
- field_name:自动编号字段
- prefix:前缀
- current_no:当前编号值
计算字段新编号时，首先查此表，如果此表无记录，自动插入一条记录

**Comment by steedos** [comment]
可参考Salesforce：
![image](https://user-images.githubusercontent.com/3104826/39349810-daade3d6-4a2e-11e8-9475-85224ae658f4.png)

**Comment by hotlong** [comment]
https://developer.salesforce.com/forums/?id=906F00000009tpQIAQ

Salesforce 没有那么先进。如果设置了 {YYYY}-{MM}-{DD}-{0000}，并不会每天从1开始重新编号

**Comment by hotlong** [comment]
已完成
